platform :ios, '7.1'
pod 'AFNetworking', '~> 2.2'
pod 'google-cast-sdk', '~> 2.2'
pod 'BlocksKit', '~> 2.2.3'
pod 'TransformerKit', '~> 0.5.0'
pod 'InflectorKit', '~> 0.0.1'
pod 'FormatterKit', '~> 1.5.1'
pod 'Mantle', '~> 1.5'
pod 'hpple', '~> 0.2.0'
